---
incline:
  gcs_bucket: robotblake-sandbox
  single_page_app: true
  prefix: incline
  subdomain: true
bucket-time:
  gcs_bucket: bucket-time
  single_page_app: false
pibal:
  gcs_bucket: mozanalysis
  single_page_app: false
fenix-migration:
  gcs_bucket: fenix-migration
  single_page_app: false
data-club-demo:
  gcs_bucket: data-club-demo-project-1
  public: true
  subdomain: true
partybal:
  gcs_bucket: partybal
  single_page_app: false
mps-deploys:
  gcs_bucket: monitoring-queries
  prefix: static
  public: true
data-health-monitor:
  gcs_bucket: data-health-monitor
  prefix: static
data-steward-stats:
  gcs_bucket: data-steward-stats
  public: true
mad-reports:
  gcs_bucket: mad-reports
  single_page_app: false
